# Exemple de SealedSecret pour Redis
# Generer avec :
#
#   kubectl create secret generic redis-credentials \
#     --from-literal=password=RedisSecr3t! \
#     --dry-run=client -o yaml | kubeseal --format yaml > sealed-secret.yaml
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: restaurant
spec:
  encryptedData:
    password: AgCE8jPLACEHOLDER_RUN_KUBESEAL_TO_GENERATE_REAL_VALUES
  template:
    metadata:
      name: redis-credentials
      namespace: restaurant
    type: Opaque
