# /!\ En production, utiliser Sealed Secrets ou External Secrets (Phase 7)
# Ces secrets sont encodés en base64, PAS chiffres

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: restaurant
type: Opaque
data:
  username: cG9zdGdyZXM=          # postgres
  password: cG9zdGdyZXM=          # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: restaurant
type: Opaque
data:
  password: cmVkaXNfc2VjcmV0      # redis_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: restaurant
type: Opaque
data:
  username: bW9uZ28=              # mongo
  password: bW9uZ28=              # mongo
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: restaurant
type: Opaque
data:
  nextauth-secret: ZGV2LXNlY3JldC1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # dev-secret-change-in-production
