apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-order
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: restauranthub
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: restauranthub

  source:
    repoURL: https://github.com/nde18/restauranthub.git
    targetRevision: main
    path: helm/charts/restaurant-service
    helm:
      valueFiles:
        - ../../../helm/values/service-order.yaml
        - ../../../gitops/env/dev/service-order.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: restaurant

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m1s
        factor: 2
