name: ""
replicas: 1

image:
  repository: ghcr.io/nde18/restauranthub/
  name: ""
  tag: ""
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 8080

headlessService:
  port: 5432

statefulSet:
  replicas: 1
  countainers:
    name: postgres
    image: postgres:15-alpine
    containerPort: 5432
  envFromSecrets:
    - name: postgres-credentials
      key: username
      envVar: POSTGRES_USER
    - name: postgres-credentials
      key: password
      envVar: POSTGRES_PASSWORD
  env: {}
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  readinessProbe:
    exec:
      command:
        - "pg_isready"
        - "-U"
        - "postgres"
    periodSeconds: 10
  volumeMounts:
    - name: data
      mountPath: /var/lib/postgresql/data

volumeClaimTemplates:
  name: data
  storageClassName: local-path
  accessModes: ["ReadWriteOnce"]
  storage: 1Gi

env: {}
envFromConfigMaps: []
envFromSecrets: []
# envFromSecrets format :
#   - name: secret-name
#     key: secret-key
#     envVar: ENV_VAR_NAME

configMap:
  enabled: false
  data: {}

probes:
  startup:
    enabled: true
    path: /actuator/health
    failureThreshold: 30
    periodSeconds: 10
  liveness:
    enabled: true
    path: /actuator/health/liveness
    periodSeconds: 15
    failureThreshold: 3
  readiness:
    enabled: true
    path: /actuator/health/readiness
    periodSeconds: 10
    failureThreshold: 3

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilization: 80

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

ingress:
  enabled: false
  className: nginx
  annotations: {}
  paths: []
  # paths format :
  #   - path: /api/v1/users
  #     pathType: Prefix
  host: ""

labels: {}
annotations: {}
