apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: restauranthub
  namespace: argocd
spec:
  description: Projet RestaurantHub — microservices platform

  sourceRepos:
    - 'https://github.com/nde18/restauranthub.git'

  destinations:
    - namespace: restaurant
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: true
